#!/usr/bin/env python3
"""Generate and validate Sixth Street's disposable cross-surface run state."""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
import zipfile


ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "state" / "sixthstreet-state.config.json"
DEFAULT_OUTPUT = ROOT / ".sixthstreet-state"
MAIN_NS = "http://schemas.openxmlformats.org/spreadsheetml/2006/main"
DOC_REL_NS = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
PKG_REL_NS = "http://schemas.openxmlformats.org/package/2006/relationships"


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def stable_json(value: object) -> str:
    return json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def sha256_file(path: Path) -> str:
    return sha256_bytes(path.read_bytes())


def run(command: list[str], cwd: Path = ROOT) -> str:
    result = subprocess.run(
        command,
        cwd=cwd,
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    return result.stdout


def run_optional(command: list[str], cwd: Path = ROOT) -> str | None:
    result = subprocess.run(
        command,
        cwd=cwd,
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    return result.stdout if result.returncode == 0 else None


def render_product_principles(data: dict) -> str:
    lines = [
        "<!-- Generated by scripts/sixthstreet-state.py render. Edit state/sixthstreet-product-principles.json instead. -->",
        f"# {data['title']}",
        "",
        "This is the compact producer for settled product judgment that otherwise has to",
        "be reconstructed from scattered reviews, specs, instructions, and history. It",
        "does not choose the next feature or settle a new consequential taste decision.",
        "",
        "## Settled",
        "",
    ]
    for item in data["settled"]:
        lines.extend(
            [
                f"### {item['id']}",
                "",
                item["principle"],
                "",
                f"Evidence: {'; '.join(item['evidence'])}",
                "",
            ]
        )
    lines.extend(["## Provisional or local", ""])
    lines.extend(f"- {item}" for item in data["provisionalOrLocal"])
    lines.extend(["", "## Rejected calibration", ""])
    lines.extend(f"- {item}" for item in data["rejectedCalibration"])
    return "\n".join(lines) + "\n"


def shared_strings(archive: zipfile.ZipFile) -> list[str]:
    try:
        root = ET.fromstring(archive.read("xl/sharedStrings.xml"))
    except KeyError:
        return []
    result = []
    for item in root.findall(f"{{{MAIN_NS}}}si"):
        result.append("".join(node.text or "" for node in item.iter(f"{{{MAIN_NS}}}t")))
    return result


def sheet_paths(archive: zipfile.ZipFile) -> dict[str, str]:
    workbook = ET.fromstring(archive.read("xl/workbook.xml"))
    relationships = ET.fromstring(archive.read("xl/_rels/workbook.xml.rels"))
    rels = {
        item.attrib["Id"]: item.attrib["Target"]
        for item in relationships.findall(f"{{{PKG_REL_NS}}}Relationship")
    }
    paths: dict[str, str] = {}
    sheets = workbook.find(f"{{{MAIN_NS}}}sheets")
    if sheets is None:
        raise ValueError("workbook has no worksheets")
    for sheet in sheets:
        rel_id = sheet.attrib[f"{{{DOC_REL_NS}}}id"]
        target = rels[rel_id].lstrip("/")
        if not target.startswith("xl/"):
            target = f"xl/{target}"
        paths[sheet.attrib["name"]] = target
    return paths


def cell_text(cell: ET.Element, strings: list[str]) -> str:
    cell_type = cell.attrib.get("t")
    if cell_type == "inlineStr":
        return "".join(node.text or "" for node in cell.iter(f"{{{MAIN_NS}}}t"))
    value = cell.find(f"{{{MAIN_NS}}}v")
    raw = "" if value is None or value.text is None else value.text
    if cell_type == "s" and raw:
        return strings[int(raw)]
    if cell_type == "b":
        return "TRUE" if raw == "1" else "FALSE"
    return raw


def read_xlsx_cells(path: Path, requested: dict[str, set[str]]) -> dict[str, str]:
    result: dict[str, str] = {}
    with zipfile.ZipFile(path) as archive:
        strings = shared_strings(archive)
        paths = sheet_paths(archive)
        for sheet, addresses in requested.items():
            if sheet not in paths:
                raise ValueError(f"missing worksheet: {sheet}")
            root = ET.fromstring(archive.read(paths[sheet]))
            found = {}
            for cell in root.iter(f"{{{MAIN_NS}}}c"):
                address = cell.attrib.get("r")
                if address in addresses:
                    found[address] = cell_text(cell, strings)
            for address in addresses:
                result[f"{sheet}!{address}"] = found.get(address, "")
    return result


def fetch_sheet(config: dict, provided_export: Path | None) -> tuple[dict[str, str], str]:
    requested = {
        group["sheet"]: set(group["addresses"])
        for group in config["sources"]["sheet"]["cells"].values()
    }
    if provided_export:
        return read_xlsx_cells(provided_export, requested), str(provided_export)
    with tempfile.TemporaryDirectory(prefix="sixthstreet-sheet-") as directory:
        export = Path(directory) / "AI-Project-Runway.xlsx"
        sheet = config["sources"]["sheet"]
        run(
            [
                "rclone",
                "backend",
                "copyid",
                sheet["rcloneRemote"],
                sheet["spreadsheetId"],
                str(export),
            ]
        )
        return read_xlsx_cells(export, requested), f"rclone:{sheet['spreadsheetId']}"


def fetch_github(config: dict) -> dict:
    source = config["sources"]["github"]
    raw = run(
        [
            "gh",
            "issue",
            "view",
            str(source["issue"]),
            "--repo",
            source["repo"],
            "--json",
            "number,title,state,updatedAt,url,body",
        ]
    )
    return json.loads(raw)


def fetch_git() -> dict:
    status = run(["git", "status", "--porcelain=v1", "-z"])
    worktree_hash = hashlib.sha256()
    worktree_hash.update(run(["git", "diff", "--binary", "HEAD"]).encode("utf-8"))
    untracked = [
        item for item in run(["git", "ls-files", "--others", "--exclude-standard", "-z"]).split("\0")
        if item
    ]
    for name in sorted(untracked):
        path = ROOT / name
        worktree_hash.update(name.encode("utf-8"))
        worktree_hash.update(b"\0")
        if path.is_file():
            worktree_hash.update(path.read_bytes())
    upstream = run_optional(
        ["git", "rev-parse", "--abbrev-ref", "--symbolic-full-name", "@{upstream}"]
    )
    return {
        "root": str(ROOT),
        "branch": run(["git", "branch", "--show-current"]).strip(),
        "head": run(["git", "rev-parse", "HEAD"]).strip(),
        "upstream": upstream.strip() if upstream else None,
        "dirty": bool(status),
        "changes": [item for item in status.split("\0") if item],
        "workingTreeSha256": worktree_hash.hexdigest(),
    }


def source_entry(reference: str, value: str) -> dict:
    return {
        "ref": reference,
        "value": value,
        "sha256": sha256_bytes(value.encode("utf-8")),
    }


def build_checks(config: dict, sheet: dict[str, str], github: dict, rendered: str) -> list[dict]:
    contract = (ROOT / config["contractFile"]).read_text(encoding="utf-8")
    agents = (ROOT / "AGENTS.md").read_text(encoding="utf-8")
    sheet_text = "\n".join(sheet.values())
    issue_body = github.get("body", "")
    view = (ROOT / config["productPrinciplesView"]).read_text(encoding="utf-8")
    task_config = config["activeTask"]
    github_config = config["sources"]["github"]
    task_values = {
        address: sheet.get(f"Sixthstreet Prep!{address}", "").strip()
        for address in task_config["requiredCells"]
    }
    raw_checks = [
        ("contract-a1", "A1 — authoritative activation" in contract, "contract contains A1"),
        ("contract-a2", "A2 — terminal continuation" in contract, "contract contains A2"),
        ("contract-b1", "P0-B decision-authority gate" in contract, "contract contains B1 gate"),
        ("programmatic-state", "programmatic state path" in contract.lower(), "contract requires the programmatic state path"),
        ("assumption-exposure", "starting assumptions" in contract, "contract requires assumptions and falsifiers"),
        ("agents-activation", "npm run sixthstreet:run" in agents, "repo AGENTS activates the single state entry point"),
        ("product-view-generated", view == rendered, "product principles view matches its JSON producer"),
        ("sheet-two-contracts", all(token in sheet_text for token in ["P0-A", "A1", "A2", "P0-B", "B1"]), "Sheet names both P0 contracts and all three invariants"),
        ("sheet-programmatic", "programmatic" in sheet_text and "Pi" in sheet_text, "Sheet records the programmatic state requirement and existing Pi path"),
        ("issue-two-contracts", "P0-A" in issue_body and "P0-B" in issue_body, "issue ledger has the converged P0 model"),
        ("issue-not-stale-taxonomy", "Ranked P0 failure classes" not in issue_body and "12 P0" not in issue_body, "issue omits the superseded broad taxonomy"),
        ("task-required-fields", all(task_values.values()), "canonical task row has every required field"),
        ("task-identity", task_config["titleIncludes"] in task_values["A22"], "canonical task title matches configured identity"),
        ("task-priority", task_values["F22"] == task_config["priority"], "canonical task has configured priority"),
        ("task-status", task_values["G22"] == task_config["status"], "canonical task has configured active status"),
        ("task-terminal-gate", task_values["E22"].startswith("PASS") and "write" in task_values["E22"].lower(), "canonical task has an observable write-aware terminal gate"),
        ("github-identity", github.get("number") == github_config["issue"] and github_config["titleIncludes"] in github.get("title", ""), "GitHub ledger identity matches configuration"),
        ("github-state", github.get("state") == github_config["expectedState"], "GitHub repair ledger is open"),
        ("github-body", bool(issue_body.strip()), "GitHub repair ledger body is nonempty"),
    ]
    return [
        {"id": check_id, "status": "pass" if passed else "fail", "detail": detail}
        for check_id, passed, detail in raw_checks
    ]


def task_from_sheet(sheet: dict[str, str]) -> dict:
    def value(address: str) -> dict:
        return source_entry(f"sheet:Sixthstreet Prep!{address}", sheet.get(f"Sixthstreet Prep!{address}", ""))

    return {
        "id": "sixthstreet-prep-22",
        "canonicalRef": "sheet:Sixthstreet Prep!A22:H22",
        "title": value("A22"),
        "objective": value("B22"),
        "deliverable": value("C22"),
        "nextAction": value("D22"),
        "terminalGate": value("E22"),
        "priority": value("F22"),
        "status": value("G22"),
        "notes": value("H22"),
    }


def markdown_snapshot(snapshot: dict) -> str:
    task = snapshot["task"]
    checks = snapshot["checks"]
    lines = [
        "# Sixth Street generated state",
        "",
        f"Run: `{snapshot['runId']}`  ",
        f"Generated: `{snapshot['generatedAt']}`  ",
        f"Contract revision: `{snapshot['revisions']['contract']}`",
        "",
        "This is a disposable read model generated from live owners. It is not a",
        "product decision or a replacement for the Sheet, GitHub, ChatGPT Project,",
        "or local Git.",
        "",
        "## Active task",
        "",
        f"- Source: `{task['canonicalRef']}`",
        f"- Title: {task['title']['value']}",
        f"- Priority/status: {task['priority']['value']} / {task['status']['value']}",
        f"- Objective: {task['objective']['value']}",
        f"- Next action: {task['nextAction']['value']}",
        f"- Terminal gate: {task['terminalGate']['value']}",
        "",
        "## Current implementation",
        "",
        f"- Local branch/head: `{snapshot['sources']['localGit']['branch']}` / `{snapshot['sources']['localGit']['head']}`",
        f"- Dirty: `{str(snapshot['sources']['localGit']['dirty']).lower()}`",
        f"- GitHub issue: [{snapshot['sources']['github']['title']}]({snapshot['sources']['github']['url']})",
        f"- Sheet retrieval: `{snapshot['sources']['sheet']['retrieval']}`",
        "",
        "## Contract invariants",
        "",
    ]
    for invariant in snapshot["invariants"]:
        lines.append(f"- **{invariant['id']} — {invariant['name']}:** {invariant['requirement']}")
    lines.extend(["", "## Deterministic checks", ""])
    for check in checks:
        lines.append(f"- `{check['status'].upper()}` {check['id']}: {check['detail']}")
    lines.extend(["", "## Expected ChatGPT Project sources", ""])
    for item in snapshot["projectDelivery"]["requiredSources"]:
        if item.get("sha256"):
            lines.append(f"- `{item['name']}` — `{item['sha256']}`")
        else:
            lines.append(f"- `{item['name']}` — generated after this snapshot")
    lines.extend(
        [
            "",
            "A fresh Project chat must verify that it activated this state packet plus",
            "the current contract, product principles, source map, and layer map. The",
            "browser receipt remains an external gate because ChatGPT Projects have no",
            "direct local-folder access.",
        ]
    )
    return "\n".join(lines) + "\n"


def load_fixture(path: Path) -> tuple[dict[str, str], dict, dict]:
    fixture = read_json(path)
    return fixture["sheet"], fixture["github"], fixture["git"]


def build_snapshot(args: argparse.Namespace) -> int:
    config = read_json(CONFIG_PATH)
    product = read_json(ROOT / config["productPrinciplesFile"])
    rendered = render_product_principles(product)
    if args.fixture:
        if os.environ.get("SIXTHSTREET_ALLOW_FIXTURE") != "1":
            print("fixture input is test-only; set SIXTHSTREET_ALLOW_FIXTURE=1", file=sys.stderr)
            return 2
        sheet, github, git = load_fixture(args.fixture)
        retrieval = f"fixture:{args.fixture}"
    else:
        sheet, retrieval = fetch_sheet(config, args.sheet_export)
        github = fetch_github(config)
        git = fetch_git()

    checks = build_checks(config, sheet, github, rendered)
    generated_at = dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()
    contract_hash = sha256_file(ROOT / config["contractFile"])
    run_id = f"{generated_at.replace(':', '').replace('-', '')}-{contract_hash[:8]}"
    required_sources = []
    for source in config["sources"]["chatgptProject"]["requiredSources"]:
        local_name = source["path"] if isinstance(source, dict) else source
        project_name = source.get("projectName", local_name) if isinstance(source, dict) else source
        path = ROOT / local_name
        required_sources.append(
            {
                "name": project_name,
                "localPath": local_name,
                "sha256": sha256_file(path) if path.exists() else None,
            }
        )
    snapshot = {
        "schemaVersion": config["schemaVersion"],
        "runId": run_id,
        "generatedAt": generated_at,
        "project": config["project"],
        "task": task_from_sheet(sheet),
        "invariants": config["invariants"],
        "phases": config["phases"],
        "decision": {
            "status": "preserve-unresolved",
            "rule": "Models expose assumptions, evidence, conflicts, and residual choices; they do not settle a consequential owner decision."
        },
        "sources": {
            "sheet": {
                "spreadsheetId": config["sources"]["sheet"]["spreadsheetId"],
                "retrieval": retrieval,
                "cells": [source_entry(f"sheet:{key}", value) for key, value in sorted(sheet.items())],
            },
            "github": {
                "repo": config["sources"]["github"]["repo"],
                "issue": github.get("number"),
                "title": github.get("title"),
                "state": github.get("state"),
                "updatedAt": github.get("updatedAt"),
                "url": github.get("url"),
                "bodySha256": sha256_bytes(github.get("body", "").encode("utf-8")),
            },
            "localGit": git,
        },
        "revisions": {
            "contract": contract_hash,
            "productPrinciples": sha256_file(ROOT / config["productPrinciplesFile"]),
            "sourceMap": sha256_file(ROOT / "Sixth-Street-source-map-current.md"),
            "layerMap": sha256_file(ROOT / config["layerMapFile"]),
            "ledger": sha256_file(ROOT / config["issueLedgerFile"]),
        },
        "checks": checks,
        "projectDelivery": {
            "projectId": config["sources"]["chatgptProject"]["projectId"],
            "url": config["sources"]["chatgptProject"]["url"],
            "requiredSources": required_sources,
            "transientPacket": "sixthstreet-state-current.md",
            "liveVerification": "external-browser-gate",
        },
        "writeback": {
            "sheetTargets": ["Paths!E3:L3", "Sixthstreet Prep!A22:H22", "20x Experiment!C13:H13"],
            "githubIssue": config["sources"]["github"]["url"],
            "completionRequiresReread": True,
        },
    }

    output = args.output.resolve()
    output.mkdir(parents=True, exist_ok=True)
    json_path = output / "current.json"
    md_path = output / "sixthstreet-state-current.md"
    json_path.write_text(stable_json(snapshot), encoding="utf-8")
    md_path.write_text(markdown_snapshot(snapshot), encoding="utf-8")
    upload_manifest = {
        "schemaVersion": 1,
        "runId": run_id,
        "sources": [
            {**item, "path": str((ROOT / item["name"]).resolve())}
            for item in required_sources
            if item["name"] != "sixthstreet-state-current.md"
        ]
        + [
            {
                "name": "sixthstreet-state-current.md",
                "path": str(md_path),
                "sha256": sha256_file(md_path),
            }
        ],
    }
    (output / "project-upload-manifest.json").write_text(stable_json(upload_manifest), encoding="utf-8")
    print(stable_json({"snapshot": str(json_path), "projectPacket": str(md_path), "checks": checks}), end="")
    failed = [check for check in checks if check["status"] == "fail"]
    return 1 if args.strict and failed else 0


def render_command(args: argparse.Namespace) -> int:
    config = read_json(CONFIG_PATH)
    product = read_json(ROOT / config["productPrinciplesFile"])
    rendered = render_product_principles(product)
    target = ROOT / config["productPrinciplesView"]
    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8") != rendered:
            print(f"stale generated view: {target}", file=sys.stderr)
            return 1
        return 0
    target.write_text(rendered, encoding="utf-8")
    print(target)
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="command", required=True)
    render = subparsers.add_parser("render")
    render.add_argument("--check", action="store_true")
    snapshot = subparsers.add_parser("snapshot")
    snapshot.add_argument("--sheet-export", type=Path)
    snapshot.add_argument("--fixture", type=Path)
    snapshot.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    snapshot.add_argument("--strict", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.command == "render":
        return render_command(args)
    if args.command == "snapshot":
        return build_snapshot(args)
    raise AssertionError(args.command)


if __name__ == "__main__":
    raise SystemExit(main())
